version: "3"

services:

  runtime-setup:
    image: netty-codec-quic-centos6:centos-6-1.8
    build:
      args:
        java_version : "adopt@1.8.0-272"

  build:
    image: netty-codec-quic-centos6:centos-6-1.8

  build-clean:
    image: netty-codec-quic-centos6:centos-6-1.8

  shell:
    image: netty-codec-quic-centos6:centos-6-1.8
