version: "3"

services:

  runtime-setup:
    image: netty-codec-quic-centos6:default
    build:
      context: ../
      dockerfile: docker/Dockerfile.centos6

  common: &common
    image: netty-codec-quic-centos6:default
    depends_on: [runtime-setup]
    volumes:
      - ~/.ssh:/root/.ssh:delegated
      - ~/.gnupg:/root/.gnupg:delegated
      - ..:/code:delegated
    working_dir: /code

  build:
    <<: *common
    command: /bin/bash -cl "mvn clean package"


  build-leak:
    <<: *common
    command: /bin/bash -cl "mvn -Pleak clean package"


  build-clean:
    <<: *common
    command: /bin/bash -cl "mvn clean package"

  deploy:
    <<: *common
    command: /bin/bash -cl "mvn clean deploy -DskipTests=true"
    volumes:
      - ~/.ssh:/root/.ssh
      - ~/.gnupg:/root/.gnupg
      - ~/.m2/settings.xml:/root/.m2/settings.xml
      - ..:/code

  deploy-clean:
    <<: *common
    command: /bin/bash -cl "mvn clean deploy -DskipTests=true"
    volumes:
      - ~/.ssh:/root/.ssh
      - ~/.gnupg:/root/.gnupg
      - ~/.m2/settings.xml:/root/.m2/settings.xml
      - ..:/code

  stage-snapshot:
    <<: *common
    volumes:
      - ~/.ssh:/root/.ssh
      - ~/.gnupg:/root/.gnupg
      - ~/local-staging:/root/local-staging
      - ..:/code
    command: /bin/bash -cl "mvn clean package org.sonatype.plugins:nexus-staging-maven-plugin:deploy -DaltStagingDirectory=/root/local-staging -DskipRemoteStaging=true -DskipTests=true"

  shell:
    <<: *common
    environment:
      - SONATYPE_USER
      - SONATYPE_PASSWORD
    volumes:
      - ~/.ssh:/root/.ssh:delegated
      - ~/.gnupg:/root/.gnupg:delegated
      - ~/.m2:/root/.m2:delegated
      - ~/.gitconfig:/root/.gitconfig:delegated
      - ~/.gitignore:/root/.gitignore:delegated
      - ..:/code:delegated
    entrypoint: /bin/bash
