version: "3"

services:

  runtime-setup:
    image: netty-codec-quic-centos6:centos-6-1.8
    build:
      args:
        java_version : "8.0.382-zulu"

  build:
    image: netty-codec-quic-centos6:centos-6-1.8

  build-leak:
    image: netty-codec-quic-centos6:centos-6-1.8

  build-clean:
    image: netty-codec-quic-centos6:centos-6-1.8

  deploy:
    image: netty-codec-quic-centos6:centos-6-1.8

  deploy-clean:
    image: netty-codec-quic-centos6:centos-6-1.8

  stage-snapshot:
    image: netty-codec-quic-centos6:centos-6-1.8

  stage-release:
    image: netty-codec-quic-centos6:centos-6-1.8

  shell:
    image: netty-codec-quic-centos6:centos-6-1.8
