name: Build project

on:
  push:
    branches: [ main ]

  schedule:
    - cron: '30 7 * * 1'  # At 07:30 on Monday, every Monday.

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-linux-x86_64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Enable caching of Docker layers
      - uses: satackey/action-docker-layer-caching@v0.0.11
        continue-on-error: true
        with:
          key: build-linux-x86_64-docker-cache-{hash}
          restore-keys: |
            build-linux-x86_64-docker-cache-

      - name: Build docker image
        run: docker-compose -f docker/docker-compose.centos-6.yaml -f docker/docker-compose.centos-6.18.yaml build

      - name: Build project without leak detection
        run: docker-compose -f docker/docker-compose.centos-6.yaml -f docker/docker-compose.centos-6.18.yaml run build | tee build.output

      - name: Checking for test failures
        run: ./.github/scripts/check_build_result.sh build.output

      - uses: actions/upload-artifact@v2
        if: ${{ failure() }}
        with:
          name: target
          path: "**/target/"
