# ----------------------------------------------------------------------------
# Copyright 2021 The Netty Project
#
# The Netty Project licenses this file to you under the Apache License,
# version 2.0 (the "License"); you may not use this file except in compliance
# with the License. You may obtain a copy of the License at:
#
#   https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
# ----------------------------------------------------------------------------
name: Build project

on:
  push:
    branches: [ main ]

  schedule:
    - cron: '30 7 * * 1'  # At 07:30 on Monday, every Monday.

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  MAVEN_OPTS: -Dhttp.keepAlive=false -Dmaven.wagon.http.pool=false -Dmaven.wagon.http.retryhandler.count=5 -Dmaven.wagon.httpconnectionManager.ttlSeconds=240

jobs:
  build-linux-x86_64:
    runs-on: ubuntu-latest
    name: linux-x86_64
    steps:
      - uses: actions/checkout@v2

      # Caching of maven dependencies
      - uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: build-linux-x86_64-maven-cache-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            build-linux-x86_64-maven-cache-

      # Enable caching of Docker layers
      - uses: satackey/action-docker-layer-caching@v0.0.11
        continue-on-error: true
        with:
          key: build-linux-x86_64-docker-cache-{hash}
          restore-keys: |
            build-linux-x86_64-docker-cache-

      - name: Build docker image
        run: docker-compose -f docker/docker-compose.centos-6.yaml -f docker/docker-compose.centos-6.18.yaml build

      - name: Build project without leak detection
        run: docker-compose -f docker/docker-compose.centos-6.yaml -f docker/docker-compose.centos-6.18.yaml run build | tee build.output

      - name: Checking for test failures
        run: ./.github/scripts/check_build_result.sh build.output

      - uses: actions/upload-artifact@v2
        if: ${{ failure() }}
        with:
          name: target
          path: "**/target/"

  build-linux-aarch64:
    runs-on: ubuntu-latest
    name: linux-aarch64
    steps:
      - uses: actions/checkout@v2

      # Caching of maven dependencies
      - uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: build-linux-aarch64-maven-cache-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            build-linux-aarch64-maven-cache-

      # Enable caching of Docker layers
      - uses: satackey/action-docker-layer-caching@v0.0.11
        continue-on-error: true
        with:
          key: build-linux-aarch64-docker-cache-{hash}
          restore-keys: |
            build-linux-aarch64-docker-cache-

      - name: Build docker image
        run: docker-compose -f docker/docker-compose.centos-7.yaml build

      - name: Build project without leak detection
        run: docker-compose -f docker/docker-compose.centos-7.yaml run cross-compile-aarch64-build

      - uses: actions/upload-artifact@v2
        if: ${{ failure() }}
        with:
          name: target
          path: "**/target/"

  build-windows:
    runs-on: windows-2016
    name: windows-x86_64
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: 8

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          target: x86_64-pc-windows-msvc
          override: true

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.0.2

      - name: Configuring Developer Command Prompt
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x86_amd64

      - name: Install tools
        uses: crazy-max/ghaction-chocolatey@v1
        with:
          args: install ninja nasm

      # Cache .m2/repository
      - uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: windows-x86_64-maven-cache-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            windows-x86_64-maven-cache-

      - name: Build project
        run: ./mvnw.cmd --file pom.xml clean package

      - uses: actions/upload-artifact@v2
        if: ${{ failure() }}
        with:
          name: build-windows-target
          path: "**/target/"
