name: Deploy project

on:
  push:
    branches: [ main ]

  schedule:
    - cron: '30 7 * * 1'  # At 07:30 on Monday, every Monday.

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy-linux-x86_64:
    runs-on: ubuntu-latest
    steps:
      - uses: s4u/maven-settings-action@v2.2.0
        with:
          servers: |
            [{
                "id": "sonatype-nexus-snapshots",
                "username": "${{ secrets.SONATYPE_USERNAME }}",
                "password": "${{ secrets.SONATYPE_PASSWORD }}"
            }]

      - uses: actions/checkout@v2

      # Enable caching of Docker layers
      - uses: satackey/action-docker-layer-caching@v0.0.8
        continue-on-error: true
        with:
          key: deploy-linux-x86_64-docker-cache-{hash}
          restore-keys: |
            deploy-linux-x86_64-docker-cache-

      - name: Build docker image
        run: docker-compose -f docker/docker-compose.centos-6.yaml -f docker/docker-compose.centos-6.18.yaml build

      - name: Deploy project snapshot to sonatype
        run: docker-compose -f docker/docker-compose.centos-6.yaml -f docker/docker-compose.centos-6.18.yaml run deploy
