# ----------------------------------------------------------------------------
# Copyright 2021 The Netty Project
#
# The Netty Project licenses this file to you under the Apache License,
# version 2.0 (the "License"); you may not use this file except in compliance
# with the License. You may obtain a copy of the License at:
#
#   https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
# ----------------------------------------------------------------------------
name: Release

on:
  # Releases can only be triggered via the action tab
  workflow_dispatch:

env:
  MAVEN_OPTS: -Dhttp.keepAlive=false -Dmaven.wagon.http.pool=false -Dmaven.wagon.http.retryhandler.count=5 -Dmaven.wagon.httpconnectionManager.ttlSeconds=240

jobs:
  prepare-release:
    runs-on: ubuntu-latest
    steps:
      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
        with:
          # this might remove tools that are actually needed,
          # if set to "true" but frees about 6 GB
          tool-cache: false

      - uses: actions/checkout@v3
        with:
          ref: main

      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 8

      - name: Setup git configuration
        run: |
          git config --global user.email "netty-project-bot@users.noreply.github.com"
          git config --global user.name "Netty Project Bot"

      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY_PEM }}
          known_hosts: ${{ secrets.SSH_KNOWN_HOSTS }}

      # Caching of maven dependencies
      - uses: actions/cache@v3
        continue-on-error: true
        with:
          path: ~/.m2/repository
          key: prepare-release-maven-cache-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            prepare-release-maven-cache-

      - name: Prepare release with Maven
        run: |
          ./mvnw -B -ntp --file pom.xml -DskipTests=true -DpreparationGoals=clean release:prepare
          ./mvnw -B -ntp clean

      - name: Checkout tag
        run: ./.github/scripts/release_checkout_tag.sh release.properties

      - name: Upload workspace
        uses: actions/upload-artifact@v3
        with:
          name: prepare-release-workspace
          path: ${{ github.workspace }}/**

  stage-release-linux:
    runs-on: ubuntu-latest
    needs: prepare-release
    strategy:
      matrix:
        include:
          - setup: linux-x86_64
            docker-compose-build: "-f docker/docker-compose.centos-7.yaml -f docker/docker-compose.centos-7.18.yaml build"
            docker-compose-run: "-f docker/docker-compose.centos-7.yaml -f docker/docker-compose.centos-7.18.yaml run stage-release"
          - setup: linux-aarch64
            docker-compose-build: "-f docker/docker-compose.centos-7-cross.yaml build"
            docker-compose-run: "-f docker/docker-compose.centos-7-cross.yaml run cross-compile-aarch64-stage-release"

    name: stage-release-${{ matrix.setup }}

    steps:
      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
        with:
          # this might remove tools that are actually needed,
          # if set to "true" but frees about 6 GB
          tool-cache: false

      - name: Download release-workspace
        uses: actions/download-artifact@v3
        with:
          name: prepare-release-workspace
          path: ./prepare-release-workspace/

      - name: Adjust mvnw permissions
        run: chmod 755 ./prepare-release-workspace/mvnw

      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 8

      - name: Setup git configuration
        run: |
          git config --global user.email "netty-project-bot@users.noreply.github.com"
          git config --global user.name "Netty Project Bot"

      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY_PEM }}
          known_hosts: ${{ secrets.SSH_KNOWN_HOSTS }}

      # Caching of maven dependencies
      - uses: actions/cache@v3
        continue-on-error: true
        with:
          path: ~/.m2/repository
          key: staging-${{ matrix.setup }}-maven-cache-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            staging-${{ matrix.setup }}-maven-cache-

      # Enable caching of Docker layers
      - uses: jpribyl/action-docker-layer-caching@v0.1.1
        env:
          docker-cache-name: staging-${{ matrix.setup }}-cache-docker
        continue-on-error: true
        with:
          key: ${{ runner.os }}-staging-${{ env.docker-cache-name }}-{hash}
          restore-keys: |
            ${{ runner.os }}-staging-${{ env.docker-cache-name }}-

      - uses: s4u/maven-settings-action@v2.2.0
        with:
          servers: |
            [{
              "id": "sonatype-nexus-staging",
              "username": "${{ secrets.SONATYPE_USERNAME }}",
              "password": "${{ secrets.SONATYPE_PASSWORD }}"
            }]

      - name: Create local staging directory
        run: mkdir -p ~/local-staging

      - name: Build docker image
        working-directory: ./prepare-release-workspace/
        run: docker-compose ${{ matrix.docker-compose-build }}

      - name: Stage release to local staging directory
        working-directory: ./prepare-release-workspace/
        env:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          GPG_KEYNAME: ${{ secrets.GPG_KEYNAME }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
        run: docker-compose ${{ matrix.docker-compose-run }}

      - name: Upload local staging directory
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.setup }}-local-staging
          path: ~/local-staging
          if-no-files-found: error

      - name: Rollback release on failure
        working-directory: ./prepare-release-workspace/
        if: ${{ failure() }}
        # Rollback the release in case of an failure
        run: bash ./.github/scripts/release_rollback.sh release.properties netty/netty-incubator-codec-quic main

  stage-release-windows-x86_64:
    runs-on: windows-2019
    name: stage-release-windows-x86_64
    needs: prepare-release
    env:
      # Let's limit the amount of ram that is used to unpack rustup as we saw
      # failures sometimes due the fact that not enough memory could be reserved.
      RUSTUP_UNPACK_RAM: 134217728  # Use 128 MiB
    steps:
      - name: Download release-workspace
        uses: actions/download-artifact@v3
        with:
          name: prepare-release-workspace
          path: ${{ github.workspace }}/prepare-release-workspace

      - name: Setup git configuration
        run: |
          git config --global user.email "netty-project-bot@users.noreply.github.com"
          git config --global user.name "Netty Project Bot"

      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY_PEM }}
          known_hosts: ${{ secrets.SSH_KNOWN_HOSTS }}

      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 8

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          target: x86_64-pc-windows-msvc
          override: true

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.0.2

      - name: Configuring Developer Command Prompt
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x86_amd64

      - name: Import GPG key
        id: import_gpg
        uses: crazy-max/ghaction-import-gpg@v3
        with:
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}

      - name: Install tools
        uses: crazy-max/ghaction-chocolatey@v1
        with:
          args: install ninja nasm

      # Caching of maven dependencies
      - uses: actions/cache@v3
        continue-on-error: true
        with:
          path: ~/.m2/repository
          key: stage-release-windows-x86_64-maven-cache-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            stage-release-windows-x86_64-maven-cache-

      - uses: s4u/maven-settings-action@v2.2.0
        with:
          servers: |
            [{
              "id": "sonatype-nexus-staging",
              "username": "${{ secrets.SONATYPE_USERNAME }}",
              "password": "${{ secrets.SONATYPE_PASSWORD }}"
            }]

      - name: Stage release to local staging directory
        working-directory: ${{ github.workspace }}/prepare-release-workspace
        env:
          LOCAL_STAGING_DIR: ${{ github.workspace }}/prepare-release-workspace/local-staging
        run: ./mvnw.cmd -B -ntp --file pom.xml clean javadoc:jar package gpg:sign org.sonatype.plugins:nexus-staging-maven-plugin:deploy -DnexusUrl=https://oss.sonatype.org -DserverId=sonatype-nexus-staging -DaltStagingDirectory=D:\a\netty-incubator-codec-quic\netty-incubator-codec-quic\prepare-release-workspace\local-staging -DskipRemoteStaging=true -DskipTests=true -D'checkstyle.skip=true'

      - name: Upload local staging directory
        uses: actions/upload-artifact@v3
        with:
          name: windows-x86_64-local-staging
          path: ${{ github.workspace }}/prepare-release-workspace/local-staging
          if-no-files-found: error

      - name: Rollback release on failure
        working-directory: ${{ github.workspace }}/prepare-release-workspace
        if: ${{ failure() }}
        # Rollback the release in case of an failure
        run: ./.github/scripts/release_rollback.ps1 release.properties netty/netty-incubator-codec-quic main

  deploy-staged-release:
    runs-on: ubuntu-latest
    # Wait until we have staged everything
    needs: [stage-release-linux, stage-release-windows-x86_64]
    steps:
      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
        with:
          # this might remove tools that are actually needed,
          # if set to "true" but frees about 6 GB
          tool-cache: false

      - name: Download release-workspace
        uses: actions/download-artifact@v3
        with:
          name: prepare-release-workspace
          path: ./prepare-release-workspace/

      - name: Adjust mvnw permissions
        run: chmod 755 ./prepare-release-workspace/mvnw

      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 8

      - name: Setup git configuration
        run: |
          git config --global user.email "netty-project-bot@users.noreply.github.com"
          git config --global user.name "Netty Project Bot"

      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY_PEM }}
          known_hosts: ${{ secrets.SSH_KNOWN_HOSTS }}

      # Hardcode the staging artifacts that need to be downloaded.
      # These must match the matrix setups. There is currently no way to pull this out of the config.
      - name: Download windows-x86_64 staging directory
        uses: actions/download-artifact@v3
        with:
          name: windows-x86_64-local-staging
          path: ~/windows-x86_64-local-staging

      - name: Download linux-aarch64 staging directory
        uses: actions/download-artifact@v3
        with:
          name: linux-aarch64-local-staging
          path: ~/linux-aarch64-local-staging

      - name: Download linux-x86_64 staging directory
        uses: actions/download-artifact@v3
        with:
          name: linux-x86_64-local-staging
          path: ~/linux-x86_64-local-staging

      # This step takes care of merging all the previous staged repositories in a way that will allow us to deploy
      # all together with one maven command.
      - name: Merge staging repositories
        working-directory: ./prepare-release-workspace/
        run: bash ./.github/scripts/merge_local_staging.sh /home/runner/local-staging/staging ~/windows-x86_64-local-staging/staging ~/linux-aarch64-local-staging/staging ~/linux-x86_64-local-staging/staging

      # Caching of maven dependencies
      - uses: actions/cache@v3
        continue-on-error: true
        with:
          path: ~/.m2/repository
          key: deploy-staged-release-maven-cache-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            deploy-staged-release-maven-cache-

      - uses: s4u/maven-settings-action@v2.2.0
        with:
          servers: |
            [{
              "id": "sonatype-nexus-staging",
              "username": "${{ secrets.SONATYPE_USERNAME }}",
              "password": "${{ secrets.SONATYPE_PASSWORD }}"
            }]

      - name: Deploy local staged artifacts
        working-directory: ./prepare-release-workspace/
        # If we don't want to close the repository we can add -DskipStagingRepositoryClose=true
        run: ./mvnw -B -ntp --file pom.xml org.sonatype.plugins:nexus-staging-maven-plugin:deploy-staged -DnexusUrl=https://oss.sonatype.org -DserverId=sonatype-nexus-staging -DaltStagingDirectory=/home/runner/local-staging -DskipStagingRepositoryClose=true

      - name: Rollback release on failure
        working-directory: ./prepare-release-workspace/
        if: ${{ failure() }}
        # Rollback the release in case of an failure
        run: bash ./.github/scripts/release_rollback.sh release.properties netty/netty-incubator-codec-quic main
